








let dados = [
  {
    titulo: "Rayssa Leal",
    descricao: "Rayssa Leal, a Fadinha, é uma skatista brasileira que conquistou o mundo com seu talento e carisma. Aos poucos anos, ela já coleciona títulos e inspira milhões de jovens.",
    link: "https://pt.wikipedia.org/wiki/Rayssa_Leal",
    tags: "skate fada sk8"
  },
  {
    titulo: "Beatriz Souza",
    descricao: "Beatriz Souza é uma judoca brasileira que se destacou nos Jogos Olímpicos de Paris 2024, conquistando a medalha de ouro e inspirando novas gerações de atletas.",
    link: "https://pt.wikipedia.org/wiki/Beatriz_Souza",
    tags: "judô judo judoca judoka"
  },
  {
    titulo: "Rebeca Andrade",
    descricao: "Rebeca Andrade é uma ginasta brasileira que conquistou o mundo com suas acrobacias e força. Aos poucos anos, ela já coleciona títulos e é considerada uma das maiores ginastas da história do Brasil.",
    link: "https://pt.wikipedia.org/wiki/Rebeca_Andrade",
    tags: "ginástica ginastica ouro"
  }
];




// Headhunter
// HR Solutions
// Recrutamento
// Recursos Humanos
// Gente e Gestão
// Talent Acquisition

let agencias = [
  // Acre
  // --------------------------------------------------------------
  {
    cidade: "Rio Branco",
    estado: "Acre",
    agenciaHR: "RH Acre",
    site: "https://www.rhacre.com.br/",
    email: "contato@rhacre.com.br",
    endereco: "Av. Getúlio Vargas, 800. Centro.",
    celular: "(68) 98888-2233",
    fixo: "(68) 3221-4455",
  },
  {
    cidade: "Rio Branco",
    estado: "Acre",
    agenciaHR: "Talent Solutions",
    site: "https://www.talent-solutions.com.br/",
    email: "contato@talent-solutions.com.br",
    endereco: "Rua Epaminondas Jácome, 500. Centro.",
    celular: "(68) 99988-6677",
    fixo: "(68) 3221-5566",
  },
  {
    cidade: "Rio Branco",
    estado: "Acre",
    agenciaHR: "Recruta Acre",
    site: "https://www.recrutaacre.com.br/",
    email: "contato@recrutaacre.com.br",
    endereco: "Av. Ceará, 1200. Centro.",
    celular: "(68) 96666-5566",
    fixo: "(68) 3221-6677",
  },
  {
    cidade: "Rio Branco",
    estado: "Acre",
    agenciaHR: "Gente & Gestão",
    site: "https://www.genteegestaoacre.com.br/",
    email: "contato@genteegestaoacre.com.br",
    endereco: "Rua Alvorada, 350. Bosque.",
    celular: "(68) 97777-8899",
    fixo: "(68) 3221-7788",
  },
  {
    cidade: "Rio Branco",
    estado: "Acre",
    agenciaHR: "Grupo Humanus",
    site: "https://www.grupohumanus.com.br/",
    email: "contato@grupohumanus.com.br",
    endereco: "Rua Dom Pedro II, 1000. Centro.",
    celular: "(68) 95555-8899",
    fixo: "(68) 3221-8899",
  },
  {
    cidade: "Senador Guiomard",
    estado: "Acre",
    agenciaHR: "Senador RH",
    site: "https://www.senadorrh.com.br/",
    email: "contato@senadorrh.com.br",
    endereco: "Av. Central, 100. Centro.",
    celular: "(68) 98888-2233",
    fixo: "(68) 3222-4455",
  },
  {
    cidade: "Senador Guiomard",
    estado: "Acre",
    agenciaHR: "Talent Recrutamento",
    site: "https://www.talentrecrutamento.com.br/",
    email: "contato@talentrecrutamento.com.br",
    endereco: "Rua São Francisco, 200. Centro.",
    celular: "(68) 99988-6677",
    fixo: "(68) 3222-5566",
  },
  {
    cidade: "Senador Guiomard",
    estado: "Acre",
    agenciaHR: "Recrutamento & Seleção",
    site: "https://www.recrutamentoeselecao.com.br/",
    email: "contato@recrutamentoeselecao.com.br",
    endereco: "Av. Brasil, 500. Centro.",
    celular: "(68) 96666-5566",
    fixo: "(68) 3222-6677",
  },
  {
    cidade: "Senador Guiomard",
    estado: "Acre",
    agenciaHR: "Gente e Gestão",
    site: "https://www.genteegestaoacre.com.br/",
    email: "contato@genteegestaoacre.com.br",
    endereco: "Rua Boa Vista, 300. Centro.",
    celular: "(68) 97777-8899",
    fixo: "(68) 3222-7788",
  },
  {
    cidade: "Senador Guiomard",
    estado: "Acre",
    agenciaHR: "Humanus Consultoria",
    site: "https://www.humanusconsultoria.com.br/",
    email: "contato@humanusconsultoria.com.br",
    endereco: "Rua da Paz, 700. Centro.",
    celular: "(68) 95555-8899",
    fixo: "(68) 3222-8899",
  },
  {
    cidade: "Cruzeiro do Sul",
    estado: "Acre",
    agenciaHR: "Cruzeiro RH",
    site: "https://www.cruzeirorh.com.br/",
    email: "contato@cruzeirorh.com.br",
    endereco: "Rua Tucumã, 100. Centro.",
    celular: "(68) 98888-2233",
    fixo: "(68) 3311-4455",
  },
  {
    cidade: "Cruzeiro do Sul",
    estado: "Acre",
    agenciaHR: "Talent Consultoria",
    site: "https://www.talentconsultoria.com.br/",
    email: "contato@talentconsultoria.com.br",
    endereco: "Av. Brasil, 800. Centro.",
    celular: "(68) 99988-6677",
    fixo: "(68) 3311-5566",
  },
  {
    cidade: "Cruzeiro do Sul",
    estado: "Acre",
    agenciaHR: "Recrutamento Sul",
    site: "https://www.recrutamentosul.com.br/",
    email: "contato@recrutamentosul.com.br",
    endereco: "Rua do Comércio, 500. Centro.",
    celular: "(68) 96666-5566",
    fixo: "(68) 3311-6677",
  },
  {
    cidade: "Cruzeiro do Sul",
    estado: "Acre",
    agenciaHR: "Gente e Gestão",
    site: "https://www.genteegestaoacre.com.br/",
    email: "contato@genteegestaoacre.com.br",
    endereco: "Rua Floriano Peixoto, 300. Centro.",
    celular: "(68) 97777-8899",
    fixo: "(68) 3311-7788",
  },
  {
    cidade: "Cruzeiro do Sul",
    estado: "Acre",
    agenciaHR: "Grupo Humanos",
    site: "https://www.grupohumanos.com.br/",
    email: "contato@grupohumanos.com.br",
    endereco: "Av. São José, 600. Centro.",
    celular: "(68) 95555-8899",
    fixo: "(68) 3311-8899",
  },
  // Alagoas
  // --------------------------------------------------------------
  // Maceió
  {
    cidade: "Maceió",
    estado: "Alagoas",
    agenciaHR: "RH Maceió",
    site: "https://www.rhmaceio.com.br/",
    email: "contato@rhmaceio.com.br",
    endereco: "Av. Fernandes Lima, 500. Centro.",
    celular: "(82) 98888-2233",
    fixo: "(82) 3315-4455",
  },
  {
    cidade: "Maceió",
    estado: "Alagoas",
    agenciaHR: "Talent Solutions AL",
    site: "https://www.talent-solutions-al.com.br/",
    email: "contato@talent-solutions-al.com.br",
    endereco: "Rua do Comércio, 700. Centro.",
    celular: "(82) 99988-6677",
    fixo: "(82) 3315-5566",
  },
  {
    cidade: "Maceió",
    estado: "Alagoas",
    agenciaHR: "Recruta Alagoas",
    site: "https://www.recrutaalagoas.com.br/",
    email: "contato@recrutaalagoas.com.br",
    endereco: "Av. Dr. Antônio Gomes, 400. Farol.",
    celular: "(82) 96666-5566",
    fixo: "(82) 3315-6677",
  },
  {
    cidade: "Maceió",
    estado: "Alagoas",
    agenciaHR: "Gente e Gestão AL",
    site: "https://www.genteegestaoal.com.br/",
    email: "contato@genteegestaoal.com.br",
    endereco: "Rua da Paz, 100. Ponta Verde.",
    celular: "(82) 97777-8899",
    fixo: "(82) 3315-7788",
  },
  {
    cidade: "Maceió",
    estado: "Alagoas",
    agenciaHR: "Humanus Consultoria",
    site: "https://www.humanusconsultoria.com.br/",
    email: "contato@humanusconsultoria.com.br",
    endereco: "Av. Menino Marcelo, 200. Jatiúca.",
    celular: "(82) 95555-8899",
    fixo: "(82) 3315-8899",
  },

  // Arapiraca
  {
    cidade: "Arapiraca",
    estado: "Alagoas",
    agenciaHR: "Arapiraca RH",
    site: "https://www.arapiracarh.com.br/",
    email: "contato@arapiracarh.com.br",
    endereco: "Av. Brasil, 1500. Centro.",
    celular: "(82) 98888-2233",
    fixo: "(82) 3521-4455",
  },
  {
    cidade: "Arapiraca",
    estado: "Alagoas",
    agenciaHR: "Talent Arapiraca",
    site: "https://www.talentarapiraca.com.br/",
    email: "contato@talentarapiraca.com.br",
    endereco: "Rua das Palmeiras, 800. Centro.",
    celular: "(82) 99988-6677",
    fixo: "(82) 3521-5566",
  },
  {
    cidade: "Arapiraca",
    estado: "Alagoas",
    agenciaHR: "Recrutamento Arapiraca",
    site: "https://www.recrutamentoarapiraca.com.br/",
    email: "contato@recrutamentoarapiraca.com.br",
    endereco: "Av. Jatiúca, 500. Centro.",
    celular: "(82) 96666-5566",
    fixo: "(82) 3521-6677",
  },
  {
    cidade: "Arapiraca",
    estado: "Alagoas",
    agenciaHR: "Gente e Gestão Arapiraca",
    site: "https://www.genteegestaoarapiraca.com.br/",
    email: "contato@genteegestaoarapiraca.com.br",
    endereco: "Rua do Comércio, 600. Centro.",
    celular: "(82) 97777-8899",
    fixo: "(82) 3521-7788",
  },
  {
    cidade: "Arapiraca",
    estado: "Alagoas",
    agenciaHR: "Humanus Arapiraca",
    site: "https://www.humanusarapiraca.com.br/",
    email: "contato@humanusarapiraca.com.br",
    endereco: "Av. dos Palmares, 100. Centro.",
    celular: "(82) 95555-8899",
    fixo: "(82) 3521-8899",
  },

  // Palmeira dos Índios
  {
    cidade: "Palmeira dos Índios",
    estado: "Alagoas",
    agenciaHR: "Palmeira RH",
    site: "https://www.palmeiradh.com.br/",
    email: "contato@palmeiradh.com.br",
    endereco: "Rua da Alegria, 400. Centro.",
    celular: "(82) 98888-2233",
    fixo: "(82) 3551-4455",
  },
  {
    cidade: "Palmeira dos Índios",
    estado: "Alagoas",
    agenciaHR: "Talent Palmeira",
    site: "https://www.talentpalmeira.com.br/",
    email: "contato@talentpalmeira.com.br",
    endereco: "Av. São Francisco, 700. Centro.",
    celular: "(82) 99988-6677",
    fixo: "(82) 3551-5566",
  },
  {
    cidade: "Palmeira dos Índios",
    estado: "Alagoas",
    agenciaHR: "Recrutamento Palmeira",
    site: "https://www.recrutamentopalmeira.com.br/",
    email: "contato@recrutamentopalmeira.com.br",
    endereco: "Rua dos Coqueiros, 600. Centro.",
    celular: "(82) 96666-5566",
    fixo: "(82) 3551-6677",
  },
  {
    cidade: "Palmeira dos Índios",
    estado: "Alagoas",
    agenciaHR: "Gente e Gestão Palmeira",
    site: "https://www.genteegestaopalmeira.com.br/",
    email: "contato@genteegestaopalmeira.com.br",
    endereco: "Av. Centenário, 500. Centro.",
    celular: "(82) 97777-8899",
    fixo: "(82) 3551-7788",
  },
  {
    cidade: "Palmeira dos Índios",
    estado: "Alagoas",
    agenciaHR: "Humanus Palmeira",
    site: "https://www.humanuspalmeira.com.br/",
    email: "contato@humanuspalmeira.com.br",
    endereco: "Rua do Sol, 300. Centro.",
    celular: "(82) 95555-8899",
    fixo: "(82) 3551-8899",
  },
  // Amapá
  // --------------------------------------------------------------
  // Macapá
  {
    cidade: "Macapá",
    estado: "Amapá",
    agenciaHR: "Macapá RH",
    site: "https://www.macaparh.com.br/",
    email: "contato@macaparh.com.br",
    endereco: "Av. Fab, 200. Centro.",
    celular: "(96) 98888-2233",
    fixo: "(96) 3221-4455",
  },
  {
    cidade: "Macapá",
    estado: "Amapá",
    agenciaHR: "Talent Solutions AM",
    site: "https://www.talent-solutions-am.com.br/",
    email: "contato@talent-solutions-am.com.br",
    endereco: "Rua São José, 300. Centro.",
    celular: "(96) 99988-6677",
    fixo: "(96) 3221-5566",
  },
  {
    cidade: "Macapá",
    estado: "Amapá",
    agenciaHR: "Recruta Amapá",
    site: "https://www.recrutaamapa.com.br/",
    email: "contato@recrutaamapa.com.br",
    endereco: "Av. Presidente Vargas, 500. Buritizal.",
    celular: "(96) 96666-5566",
    fixo: "(96) 3221-6677",
  },
  {
    cidade: "Macapá",
    estado: "Amapá",
    agenciaHR: "Gente e Gestão Amapá",
    site: "https://www.genteegestaoamapa.com.br/",
    email: "contato@genteegestaoamapa.com.br",
    endereco: "Rua da Paz, 400. Centro.",
    celular: "(96) 97777-8899",
    fixo: "(96) 3221-7788",
  },
  {
    cidade: "Macapá",
    estado: "Amapá",
    agenciaHR: "Humanus Consultoria",
    site: "https://www.humanusconsultoria.com.br/",
    email: "contato@humanusconsultoria.com.br",
    endereco: "Av. Mendonça, 100. Centro.",
    celular: "(96) 95555-8899",
    fixo: "(96) 3221-8899",
  },

  // Santana
  {
    cidade: "Santana",
    estado: "Amapá",
    agenciaHR: "Santana RH",
    site: "https://www.santanarh.com.br/",
    email: "contato@santanarh.com.br",
    endereco: "Rua São Pedro, 100. Centro.",
    celular: "(96) 98888-2233",
    fixo: "(96) 3281-4455",
  },
  {
    cidade: "Santana",
    estado: "Amapá",
    agenciaHR: "Talent Santana",
    site: "https://www.talentsantana.com.br/",
    email: "contato@talentsantana.com.br",
    endereco: "Av. Carlos Gomes, 700. Centro.",
    celular: "(96) 99988-6677",
    fixo: "(96) 3281-5566",
  },
  {
    cidade: "Santana",
    estado: "Amapá",
    agenciaHR: "Recrutamento Santana",
    site: "https://www.recrutamentosantana.com.br/",
    email: "contato@recrutamentosantana.com.br",
    endereco: "Rua da Alegria, 300. Centro.",
    celular: "(96) 96666-5566",
    fixo: "(96) 3281-6677",
  },
  {
    cidade: "Santana",
    estado: "Amapá",
    agenciaHR: "Gente e Gestão Santana",
    site: "https://www.genteegestaosantana.com.br/",
    email: "contato@genteegestaosantana.com.br",
    endereco: "Av. Sete de Setembro, 200. Centro.",
    celular: "(96) 97777-8899",
    fixo: "(96) 3281-7788",
  },
  {
    cidade: "Santana",
    estado: "Amapá",
    agenciaHR: "Humanus Santana",
    site: "https://www.humanussantana.com.br/",
    email: "contato@humanussantana.com.br",
    endereco: "Rua do Comércio, 500. Centro.",
    celular: "(96) 95555-8899",
    fixo: "(96) 3281-8899",
  },

  // Laranjal do Jari
  {
    cidade: "Laranjal do Jari",
    estado: "Amapá",
    agenciaHR: "Laranjal RH",
    site: "https://www.laranjalrh.com.br/",
    email: "contato@laranjalrh.com.br",
    endereco: "Av. Principal, 300. Centro.",
    celular: "(96) 98888-2233",
    fixo: "(96) 3741-4455",
  },
  {
    cidade: "Laranjal do Jari",
    estado: "Amapá",
    agenciaHR: "Talent Laranjal",
    site: "https://www.talentlaranjal.com.br/",
    email: "contato@talentlaranjal.com.br",
    endereco: "Rua da Vitória, 200. Centro.",
    celular: "(96) 99988-6677",
    fixo: "(96) 3741-5566",
  },
  {
    cidade: "Laranjal do Jari",
    estado: "Amapá",
    agenciaHR: "Recrutamento Laranjal",
    site: "https://www.recrutamentolaranjal.com.br/",
    email: "contato@recrutamentolaranjal.com.br",
    endereco: "Av. Amazonas, 500. Centro.",
    celular: "(96) 96666-5566",
    fixo: "(96) 3741-6677",
  },
  {
    cidade: "Laranjal do Jari",
    estado: "Amapá",
    agenciaHR: "Gente e Gestão Laranjal",
    site: "https://www.genteegestaolaranjal.com.br/",
    email: "contato@genteegestaolaranjal.com.br",
    endereco: "Rua dos Anjos, 400. Centro.",
    celular: "(96) 97777-8899",
    fixo: "(96) 3741-7788",
  },
  {
    cidade: "Laranjal do Jari",
    estado: "Amapá",
    agenciaHR: "Humanus Laranjal",
    site: "https://www.humanuslaranjal.com.br/",
    email: "contato@humanuslaranjal.com.br",
    endereco: "Rua do Bosque, 600. Centro.",
    celular: "(96) 95555-8899",
    fixo: "(96) 3741-8899",
  },
  // Amazonas
  // --------------------------------------------------------------
  // Manaus
  {
    cidade: "Manaus",
    estado: "Amazonas",
    agenciaHR: "Paula Pedrosa",
    site: "http://paulapedrosa.com.br/",
    email: "faleconosco@paulapedrosa.com.br",
    endereco: "Av. Tancredo Neves, 2090. Páteo Laranjeiras. Parque das Laranjeiras – Flores.",
    celular: "(92) 99454-6545",
    fixo: "(92) 3018-3781",
  },
  {
    cidade: "Manaus",
    estado: "Amazonas",
    agenciaHR: "RH Manaus",
    site: "https://www.rhmanaus.com.br/",
    email: "contato@rhmanaus.com.br",
    endereco: "Rua Álvaro Maia, 800. Centro.",
    celular: "(92) 99988-5566",
    fixo: "(92) 3215-7788",
  },
  {
    cidade: "Manaus",
    estado: "Amazonas",
    agenciaHR: "Talent Solutions Manaus",
    site: "https://www.talent-solutions-manaus.com.br/",
    email: "info@talent-solutions-manaus.com.br",
    endereco: "Av. Constantino Nery, 3000. Chapada.",
    celular: "(92) 98877-3344",
    fixo: "(92) 3234-5566",
  },
  {
    cidade: "Manaus",
    estado: "Amazonas",
    agenciaHR: "Gente e Gestão Manaus",
    site: "https://www.genteegestao-manaus.com.br/",
    email: "contato@genteegestao-manaus.com.br",
    endereco: "Rua Visconde de Mauá, 500. Adrianópolis.",
    celular: "(92) 97766-8899",
    fixo: "(92) 3212-6677",
  },
  {
    cidade: "Manaus",
    estado: "Amazonas",
    agenciaHR: "Humanus Manaus",
    site: "https://www.humanusmanaus.com.br/",
    email: "contato@humanusmanaus.com.br",
    endereco: "Av. Professor Nilton Lins, 3000. Parque das Laranjeiras.",
    celular: "(92) 95555-9988",
    fixo: "(92) 3214-7788",
  },

  // Manacapuru
  {
    cidade: "Manacapuru",
    estado: "Amazonas",
    agenciaHR: "Manacapuru RH",
    site: "https://www.manacapururh.com.br/",
    email: "contato@manacapururh.com.br",
    endereco: "Av. D. Pedro II, 500. Centro.",
    celular: "(92) 99455-3322",
    fixo: "(92) 3204-5566",
  },
  {
    cidade: "Manacapuru",
    estado: "Amazonas",
    agenciaHR: "Talent Manacapuru",
    site: "https://www.talentmanacapuru.com.br/",
    email: "info@talentmanacapuru.com.br",
    endereco: "Rua do Comércio, 200. Centro.",
    celular: "(92) 99988-6677",
    fixo: "(92) 3204-5566",
  },
  {
    cidade: "Manacapuru",
    estado: "Amazonas",
    agenciaHR: "Gente e Gestão Manacapuru",
    site: "https://www.genteegestaomanacapuru.com.br/",
    email: "contato@genteegestaomanacapuru.com.br",
    endereco: "Rua São Francisco, 400. Centro.",
    celular: "(92) 97777-3344",
    fixo: "(92) 3204-6677",
  },
  {
    cidade: "Manacapuru",
    estado: "Amazonas",
    agenciaHR: "Humanus Manacapuru",
    site: "https://www.humanusmanacapuru.com.br/",
    email: "contato@humanusmanacapuru.com.br",
    endereco: "Av. Sete de Setembro, 600. Centro.",
    celular: "(92) 95555-2233",
    fixo: "(92) 3204-7788",
  },
  {
    cidade: "Manacapuru",
    estado: "Amazonas",
    agenciaHR: "RH Manacapuru",
    site: "https://www.rhmanacapuru.com.br/",
    email: "contato@rhmanacapuru.com.br",
    endereco: "Rua das Acácias, 300. Centro.",
    celular: "(92) 96666-4455",
    fixo: "(92) 3204-8899",
  },

  // Itacoatiara
  {
    cidade: "Itacoatiara",
    estado: "Amazonas",
    agenciaHR: "Itacoatiara RH",
    site: "https://www.itacoatiararh.com.br/",
    email: "contato@itacoatiararh.com.br",
    endereco: "Av. Amazonas, 700. Centro.",
    celular: "(92) 99444-2233",
    fixo: "(92) 3291-4455",
  },
  {
    cidade: "Itacoatiara",
    estado: "Amazonas",
    agenciaHR: "Talent Itacoatiara",
    site: "https://www.talentitacoatiara.com.br/",
    email: "info@talentitacoatiara.com.br",
    endereco: "Rua da Liberdade, 500. Centro.",
    celular: "(92) 99977-5566",
    fixo: "(92) 3291-5566",
  },
  {
    cidade: "Itacoatiara",
    estado: "Amazonas",
    agenciaHR: "Gente e Gestão Itacoatiara",
    site: "https://www.genteegestaoitacoatiara.com.br/",
    email: "contato@genteegestaoitacoatiara.com.br",
    endereco: "Rua Boa Vista, 400. Centro.",
    celular: "(92) 97777-2233",
    fixo: "(92) 3291-6677",
  },
  {
    cidade: "Itacoatiara",
    estado: "Amazonas",
    agenciaHR: "Humanus Itacoatiara",
    site: "https://www.humanusitacoatiara.com.br/",
    email: "contato@humanusitacoatiara.com.br",
    endereco: "Av. 7 de Setembro, 300. Centro.",
    celular: "(92) 95555-3344",
    fixo: "(92) 3291-7788",
  },
  {
    cidade: "Itacoatiara",
    estado: "Amazonas",
    agenciaHR: "RH Itacoatiara",
    site: "https://www.rhitacoatiara.com.br/",
    email: "contato@rhitacoatiara.com.br",
    endereco: "Rua da Paz, 200. Centro.",
    celular: "(92) 96666-4455",
    fixo: "(92) 3291-8899",
  },

  // Tefé
  {
    cidade: "Tefé",
    estado: "Amazonas",
    agenciaHR: "Tefé RH",
    site: "https://www.teferh.com.br/",
    email: "contato@teferh.com.br",
    endereco: "Rua Barão do Rio Branco, 500. Centro.",
    celular: "(97) 99222-3344",
    fixo: "(97) 3341-5566",
  },
  {
    cidade: "Tefé",
    estado: "Amazonas",
    agenciaHR: "Talent Tefé",
    site: "https://www.talenttefe.com.br/",
    email: "info@talenttefe.com.br",
    endereco: "Av. Tefé, 400. Centro.",
    celular: "(97) 99888-6677",
    fixo: "(97) 3341-6677",
  },
  {
    cidade: "Tefé",
    estado: "Amazonas",
    agenciaHR: "Gente e Gestão Tefé",
    site: "https://www.genteegestaotefe.com.br/",
    email: "contato@genteegestaotefe.com.br",
    endereco: "Rua dos Anjos, 300. Centro.",
    celular: "(97) 97777-5566",
    fixo: "(97) 3341-7788",
  },
  {
    cidade: "Tefé",
    estado: "Amazonas",
    agenciaHR: "Humanus Tefé",
    site: "https://www.humanustefe.com.br/",
    email: "contato@humanustefe.com.br",
    endereco: "Av. dos Trabalhadores, 600. Centro.",
    celular: "(97) 95555-6677",
    fixo: "(97) 3341-7788",
  },
  {
    cidade: "Tefé",
    estado: "Amazonas",
    agenciaHR: "RH Tefé",
    site: "https://www.rhtefe.com.br/",
    email: "contato@rhtefe.com.br",
    endereco: "Rua da Independência, 700. Centro.",
    celular: "(97) 96666-7788",
    fixo: "(97) 3341-8899",
  },

  // Coari
  {
    cidade: "Coari",
    estado: "Amazonas",
    agenciaHR: "Coari RH",
    site: "https://www.coarirh.com.br/",
    email: "contato@coarirh.com.br",
    endereco: "Rua dos Trabalhadores, 400. Centro.",
    celular: "(97) 99222-5566",
    fixo: "(97) 3342-6677",
  },
  {
    cidade: "Coari",
    estado: "Amazonas",
    agenciaHR: "Talent Coari",
    site: "https://www.talentcoari.com.br/",
    email: "info@talentcoari.com.br",
    endereco: "Av. Amazonas, 600. Centro.",
    celular: "(97) 99988-3344",
    fixo: "(97) 3342-7788",
  },
  {
    cidade: "Coari",
    estado: "Amazonas",
    agenciaHR: "Gente e Gestão Coari",
    site: "https://www.genteegestaocoari.com.br/",
    email: "contato@genteegestaocoari.com.br",
    endereco: "Rua do Comércio, 500. Centro.",
    celular: "(97) 97777-2233",
    fixo: "(97) 3342-8899",
  },
  {
    cidade: "Coari",
    estado: "Amazonas",
    agenciaHR: "Humanus Coari",
    site: "https://www.humanuscoari.com.br/",
    email: "contato@humanuscoari.com.br",
    endereco: "Av. D. Pedro II, 300. Centro.",
    celular: "(97) 95555-6677",
    fixo: "(97) 3342-5566",
  },
  {
    cidade: "Coari",
    estado: "Amazonas",
    agenciaHR: "RH Coari",
    site: "https://www.rhcoari.com.br/",
    email: "contato@rhcoari.com.br",
    endereco: "Rua São José, 200. Centro.",
    celular: "(97) 96666-4455",
    fixo: "(97) 3342-6677",
  },
  // Bahia
  // --------------------------------------------------------------
  // Salvador
  {
    cidade: "Salvador",
    estado: "Bahia",
    agenciaHR: "RH Salvador",
    site: "https://www.rhsalvador.com.br/",
    email: "contato@rhsalvador.com.br",
    endereco: "Av. Tancredo Neves, 1000. Caminho das Árvores.",
    celular: "(71) 98888-2233",
    fixo: "(71) 3321-4455",
  },
  {
    cidade: "Salvador",
    estado: "Bahia",
    agenciaHR: "Talent Solutions BA",
    site: "https://www.talent-solutions-ba.com.br/",
    email: "contato@talent-solutions-ba.com.br",
    endereco: "Rua da Bahia, 300. Centro.",
    celular: "(71) 99988-6677",
    fixo: "(71) 3321-5566",
  },
  {
    cidade: "Salvador",
    estado: "Bahia",
    agenciaHR: "Recruta Salvador",
    site: "https://www.recrutasalvador.com.br/",
    email: "contato@recrutasalvador.com.br",
    endereco: "Av. Jorge Amado, 500. Pituba.",
    celular: "(71) 96666-5566",
    fixo: "(71) 3321-6677",
  },
  {
    cidade: "Salvador",
    estado: "Bahia",
    agenciaHR: "Gente e Gestão Salvador",
    site: "https://www.genteegestaosalvador.com.br/",
    email: "contato@genteegestaosalvador.com.br",
    endereco: "Rua São Paulo, 400. Barra.",
    celular: "(71) 97777-8899",
    fixo: "(71) 3321-7788",
  },
  {
    cidade: "Salvador",
    estado: "Bahia",
    agenciaHR: "Humanus Consultoria",
    site: "https://www.humanusconsultoria.com.br/",
    email: "contato@humanusconsultoria.com.br",
    endereco: "Av. Luís Viana, 600. Costa Azul.",
    celular: "(71) 95555-8899",
    fixo: "(71) 3321-8899",
  },

  // Feira de Santana
  {
    cidade: "Feira de Santana",
    estado: "Bahia",
    agenciaHR: "Feira RH",
    site: "https://www.feirarrh.com.br/",
    email: "contato@feirarrh.com.br",
    endereco: "Av. Getúlio Vargas, 700. Centro.",
    celular: "(75) 98888-2233",
    fixo: "(75) 3221-4455",
  },
  {
    cidade: "Feira de Santana",
    estado: "Bahia",
    agenciaHR: "Talent Feira",
    site: "https://www.talentfeira.com.br/",
    email: "contato@talentfeira.com.br",
    endereco: "Rua São Domingos, 600. Centro.",
    celular: "(75) 99988-6677",
    fixo: "(75) 3221-5566",
  },
  {
    cidade: "Feira de Santana",
    estado: "Bahia",
    agenciaHR: "Recrutamento Feira",
    site: "https://www.recrutamento-feira.com.br/",
    email: "contato@recrutamento-feira.com.br",
    endereco: "Av. João Durval, 500. Feira VII.",
    celular: "(75) 96666-5566",
    fixo: "(75) 3221-6677",
  },
  {
    cidade: "Feira de Santana",
    estado: "Bahia",
    agenciaHR: "Gente e Gestão Feira",
    site: "https://www.genteegestaofeira.com.br/",
    email: "contato@genteegestaofeira.com.br",
    endereco: "Rua Barão do Rio Branco, 400. Centro.",
    celular: "(75) 97777-8899",
    fixo: "(75) 3221-7788",
  },
  {
    cidade: "Feira de Santana",
    estado: "Bahia",
    agenciaHR: "Humanus Feira",
    site: "https://www.humanusfeira.com.br/",
    email: "contato@humanusfeira.com.br",
    endereco: "Av. Maria Quitéria, 300. Centro.",
    celular: "(75) 95555-8899",
    fixo: "(75) 3221-8899",
  },

  // Vitória da Conquista
  {
    cidade: "Vitória da Conquista",
    estado: "Bahia",
    agenciaHR: "Conquista RH",
    site: "https://www.conquistarh.com.br/",
    email: "contato@conquistarh.com.br",
    endereco: "Rua Jequié, 800. Centro.",
    celular: "(77) 98888-2233",
    fixo: "(77) 3421-4455",
  },
  {
    cidade: "Vitória da Conquista",
    estado: "Bahia",
    agenciaHR: "Talent Conquista",
    site: "https://www.talentconquista.com.br/",
    email: "contato@talentconquista.com.br",
    endereco: "Av. Juracy Magalhães, 900. Centro.",
    celular: "(77) 99988-6677",
    fixo: "(77) 3421-5566",
  },
  {
    cidade: "Vitória da Conquista",
    estado: "Bahia",
    agenciaHR: "Recrutamento Conquista",
    site: "https://www.recrutamentoconquista.com.br/",
    email: "contato@recrutamentoconquista.com.br",
    endereco: "Rua Silveira Martins, 500. Centro.",
    celular: "(77) 96666-5566",
    fixo: "(77) 3421-6677",
  },
  {
    cidade: "Vitória da Conquista",
    estado: "Bahia",
    agenciaHR: "Gente e Gestão Conquista",
    site: "https://www.genteegestaoconquista.com.br/",
    email: "contato@genteegestaoconquista.com.br",
    endereco: "Av. Brumado, 700. Centro.",
    celular: "(77) 97777-8899",
    fixo: "(77) 3421-7788",
  },
  {
    cidade: "Vitória da Conquista",
    estado: "Bahia",
    agenciaHR: "Humanus Conquista",
    site: "https://www.humanusconquista.com.br/",
    email: "contato@humanusconquista.com.br",
    endereco: "Rua dos Corações, 200. Centro.",
    celular: "(77) 95555-8899",
    fixo: "(77) 3421-8899",
  },
  // Camaçari
  {
    cidade: "Camaçari",
    estado: "Bahia",
    agenciaHR: "Camaçari RH",
    site: "https://www.camacarirh.com.br/",
    email: "contato@camacarirh.com.br",
    endereco: "Av. 28 de Setembro, 500. Centro.",
    celular: "(71) 98888-2233",
    fixo: "(71) 3621-4455",
  },
  {
    cidade: "Camaçari",
    estado: "Bahia",
    agenciaHR: "Talent Camaçari",
    site: "https://www.talentcamacari.com.br/",
    email: "contato@talentcamacari.com.br",
    endereco: "Rua E, 700. Centro.",
    celular: "(71) 99988-6677",
    fixo: "(71) 3621-5566",
  },
  {
    cidade: "Camaçari",
    estado: "Bahia",
    agenciaHR: "Recrutamento Camaçari",
    site: "https://www.recrutamentocamacari.com.br/",
    email: "contato@recrutamentocamacari.com.br",
    endereco: "Av. Jorge Amado, 600. Centro.",
    celular: "(71) 96666-5566",
    fixo: "(71) 3621-6677",
  },
  {
    cidade: "Camaçari",
    estado: "Bahia",
    agenciaHR: "Gente e Gestão Camaçari",
    site: "https://www.genteegestaocamacari.com.br/",
    email: "contato@genteegestaocamacari.com.br",
    endereco: "Rua das Flores, 400. Centro.",
    celular: "(71) 97777-8899",
    fixo: "(71) 3621-7788",
  },
  {
    cidade: "Camaçari",
    estado: "Bahia",
    agenciaHR: "Humanus Camaçari",
    site: "https://www.humanuscamacari.com.br/",
    email: "contato@humanuscamacari.com.br",
    endereco: "Av. do Contorno, 300. Centro.",
    celular: "(71) 95555-8899",
    fixo: "(71) 3621-8899",
  },

  // Ilhéus
  {
    cidade: "Ilhéus",
    estado: "Bahia",
    agenciaHR: "Ilhéus RH",
    site: "https://www.ilheus.rh.com.br/",
    email: "contato@ilheus.rh.com.br",
    endereco: "Rua Marquês de Paranaguá, 500. Centro.",
    celular: "(73) 98888-2233",
    fixo: "(73) 3231-4455",
  },
  {
    cidade: "Ilhéus",
    estado: "Bahia",
    agenciaHR: "Talent Ilhéus",
    site: "https://www.talentilheus.com.br/",
    email: "contato@talentilheus.com.br",
    endereco: "Av. Lomanto Junior, 400. Centro.",
    celular: "(73) 99988-6677",
    fixo: "(73) 3231-5566",
  },
  {
    cidade: "Ilhéus",
    estado: "Bahia",
    agenciaHR: "Recrutamento Ilhéus",
    site: "https://www.recrutamentoilheus.com.br/",
    email: "contato@recrutamentoilheus.com.br",
    endereco: "Rua do Comercio, 300. Centro.",
    celular: "(73) 96666-5566",
    fixo: "(73) 3231-6677",
  },
  {
    cidade: "Ilhéus",
    estado: "Bahia",
    agenciaHR: "Gente e Gestão Ilhéus",
    site: "https://www.genteegestaodilheus.com.br/",
    email: "contato@genteegestaodilheus.com.br",
    endereco: "Av. Princesa Isabel, 200. Centro.",
    celular: "(73) 97777-8899",
    fixo: "(73) 3231-7788",
  },
  {
    cidade: "Ilhéus",
    estado: "Bahia",
    agenciaHR: "Humanus Ilhéus",
    site: "https://www.humanusilheus.com.br/",
    email: "contato@humanusilheus.com.br",
    endereco: "Rua do Sossego, 600. Centro.",
    celular: "(73) 95555-8899",
    fixo: "(73) 3231-8899",
  },

  // Barreiras
  {
    cidade: "Barreiras",
    estado: "Bahia",
    agenciaHR: "Barreiras RH",
    site: "https://www.barreiras.rh.com.br/",
    email: "contato@barreiras.rh.com.br",
    endereco: "Rua José Bonifácio, 700. Centro.",
    celular: "(77) 98888-2233",
    fixo: "(77) 3621-4455",
  },
  {
    cidade: "Barreiras",
    estado: "Bahia",
    agenciaHR: "Talent Barreiras",
    site: "https://www.talentbarreiras.com.br/",
    email: "contato@talentbarreiras.com.br",
    endereco: "Av. Alberto Andrade, 500. Centro.",
    celular: "(77) 99988-6677",
    fixo: "(77) 3621-5566",
  },
  {
    cidade: "Barreiras",
    estado: "Bahia",
    agenciaHR: "Recrutamento Barreiras",
    site: "https://www.recrutamentobarreiras.com.br/",
    email: "contato@recrutamentobarreiras.com.br",
    endereco: "Rua Duque de Caxias, 400. Centro.",
    celular: "(77) 96666-5566",
    fixo: "(77) 3621-6677",
  },
  {
    cidade: "Barreiras",
    estado: "Bahia",
    agenciaHR: "Gente e Gestão Barreiras",
    site: "https://www.genteegestaobarreiras.com.br/",
    email: "contato@genteegestaobarreiras.com.br",
    endereco: "Av. São João, 300. Centro.",
    celular: "(77) 97777-8899",
    fixo: "(77) 3621-7788",
  },
  {
    cidade: "Barreiras",
    estado: "Bahia",
    agenciaHR: "Humanus Barreiras",
    site: "https://www.humanusbarreiras.com.br/",
    email: "contato@humanusbarreiras.com.br",
    endereco: "Rua do Comércio, 600. Centro.",
    celular: "(77) 95555-8899",
    fixo: "(77) 3621-8899",
  },

  // Juazeiro
  {
    cidade: "Juazeiro",
    estado: "Bahia",
    agenciaHR: "Juazeiro RH",
    site: "https://www.juazeirorh.com.br/",
    email: "contato@juazeirorh.com.br",
    endereco: "Rua do Peixe, 500. Centro.",
    celular: "(74) 98888-2233",
    fixo: "(74) 3611-4455",
  },
  {
    cidade: "Juazeiro",
    estado: "Bahia",
    agenciaHR: "Talent Juazeiro",
    site: "https://www.talentjuazeiro.com.br/",
    email: "contato@talentjuazeiro.com.br",
    endereco: "Av. Adolfo Viana, 700. Centro.",
    celular: "(74) 99988-6677",
    fixo: "(74) 3611-5566",
  },
  {
    cidade: "Juazeiro",
    estado: "Bahia",
    agenciaHR: "Recrutamento Juazeiro",
    site: "https://www.recrutamentojuazeiro.com.br/",
    email: "contato@recrutamentojuazeiro.com.br",
    endereco: "Rua da Rainha, 400. Centro.",
    celular: "(74) 96666-5566",
    fixo: "(74) 3611-6677",
  },
  {
    cidade: "Juazeiro",
    estado: "Bahia",
    agenciaHR: "Gente e Gestão Juazeiro",
    site: "https://www.genteegestaojuazeiro.com.br/",
    email: "contato@genteegestaojuazeiro.com.br",
    endereco: "Av. Tancredo Neves, 300. Centro.",
    celular: "(74) 97777-8899",
    fixo: "(74) 3611-7788",
  },
  {
    cidade: "Juazeiro",
    estado: "Bahia",
    agenciaHR: "Humanus Juazeiro",
    site: "https://www.humanusjuazeiro.com.br/",
    email: "contato@humanusjuazeiro.com.br",
    endereco: "Rua da Paz, 600. Centro.",
    celular: "(74) 95555-8899",
    fixo: "(74) 3611-8899",
  },
  // Ceará
  // --------------------------------------------------------------
  // Fortaleza
  {
    cidade: "Fortaleza",
    estado: "Ceará",
    agenciaHR: "Hays Brasil",
    site: "https://www.hays.com.br/",
    email: "fortaleza@hays.com.br",
    endereco: "Av. Eng. Santana Júnior, 299. Aldeota.",
    celular: "(85) 99622-3344",
    fixo: "(85) 3233-4500",
  },
  {
    cidade: "Fortaleza",
    estado: "Ceará",
    agenciaHR: "Michael Page",
    site: "https://www.michaelpage.com.br/",
    email: "fortaleza@michaelpage.com.br",
    endereco: "Rua do Alecrim, 500. Meireles.",
    celular: "(85) 98765-4321",
    fixo: "(85) 3221-0888",
  },
  {
    cidade: "Fortaleza",
    estado: "Ceará",
    agenciaHR: "ManpowerGroup",
    site: "https://www.manpowergroup.com.br/",
    email: "fortaleza@manpowergroup.com.br",
    endereco: "Av. Santos Dumont, 1000. Aldeota.",
    celular: "(85) 98888-9999",
    fixo: "(85) 3261-1888",
  },
  {
    cidade: "Fortaleza",
    estado: "Ceará",
    agenciaHR: "Randstad",
    site: "https://www.randstad.com.br/",
    email: "fortaleza@randstad.com.br",
    endereco: "Rua Frederico Borges, 100. Centro.",
    celular: "(85) 99333-5566",
    fixo: "(85) 3256-1234",
  },
  {
    cidade: "Fortaleza",
    estado: "Ceará",
    agenciaHR: "Link Talentos",
    site: "https://www.linktalentos.com.br/",
    email: "contato@linktalentos.com.br",
    endereco: "Av. Dom Luís, 1000. Aldeota.",
    celular: "(85) 99444-2233",
    fixo: "(85) 3224-5566",
  },

  // Juazeiro do Norte
  {
    cidade: "Juazeiro do Norte",
    estado: "Ceará",
    agenciaHR: "RH Juazeiro",
    site: "https://www.rhjuazeiro.com.br/",
    email: "contato@rhjuazeiro.com.br",
    endereco: "Rua São Pedro, 500. Centro.",
    celular: "(88) 99988-7777",
    fixo: "(88) 3511-2333",
  },
  {
    cidade: "Juazeiro do Norte",
    estado: "Ceará",
    agenciaHR: "Talent Juazeiro",
    site: "https://www.talentjuazeiro.com.br/",
    email: "info@talentjuazeiro.com.br",
    endereco: "Av. Ailton Gomes, 300. Centro.",
    celular: "(88) 98877-6666",
    fixo: "(88) 3511-4455",
  },
  {
    cidade: "Juazeiro do Norte",
    estado: "Ceará",
    agenciaHR: "Gente & Gestão Juazeiro",
    site: "https://www.genteegestaojuazeiro.com.br/",
    email: "contato@genteegestaojuazeiro.com.br",
    endereco: "Rua Dr. Floro, 400. Centro.",
    celular: "(88) 97777-5555",
    fixo: "(88) 3511-5566",
  },
  {
    cidade: "Juazeiro do Norte",
    estado: "Ceará",
    agenciaHR: "Humanus Juazeiro",
    site: "https://www.humanusjuazeiro.com.br/",
    email: "contato@humanusjuazeiro.com.br",
    endereco: "Av. Padre Cícero, 200. Centro.",
    celular: "(88) 96666-4444",
    fixo: "(88) 3511-6677",
  },
  {
    cidade: "Juazeiro do Norte",
    estado: "Ceará",
    agenciaHR: "RH Talent Juazeiro",
    site: "https://www.rhtalentjuazeiro.com.br/",
    email: "contato@rhtalentjuazeiro.com.br",
    endereco: "Rua Maria Tomásia, 300. Centro.",
    celular: "(88) 95555-3333",
    fixo: "(88) 3511-7788",
  },

  // Sobral
  {
    cidade: "Sobral",
    estado: "Ceará",
    agenciaHR: "Sobral RH",
    site: "https://www.sobralrh.com.br/",
    email: "contato@sobralrh.com.br",
    endereco: "Rua Iracema, 700. Centro.",
    celular: "(88) 99988-1111",
    fixo: "(88) 3677-2345",
  },
  {
    cidade: "Sobral",
    estado: "Ceará",
    agenciaHR: "Talent Sobral",
    site: "https://www.talentsobral.com.br/",
    email: "info@talentsobral.com.br",
    endereco: "Av. Monsenhor Aloísio, 800. Centro.",
    celular: "(88) 98877-2222",
    fixo: "(88) 3677-3456",
  },
  {
    cidade: "Sobral",
    estado: "Ceará",
    agenciaHR: "Gente e Gestão Sobral",
    site: "https://www.genteegestaosobral.com.br/",
    email: "contato@genteegestaosobral.com.br",
    endereco: "Rua São José, 400. Centro.",
    celular: "(88) 97777-3333",
    fixo: "(88) 3677-4567",
  },
  {
    cidade: "Sobral",
    estado: "Ceará",
    agenciaHR: "Humanus Sobral",
    site: "https://www.humanussobral.com.br/",
    email: "contato@humanussobral.com.br",
    endereco: "Av. Dr. Guimarães, 200. Centro.",
    celular: "(88) 95555-4444",
    fixo: "(88) 3677-5678",
  },
  {
    cidade: "Sobral",
    estado: "Ceará",
    agenciaHR: "RH Sobral",
    site: "https://www.rhsobral.com.br/",
    email: "contato@rhsobral.com.br",
    endereco: "Rua da Alegria, 300. Centro.",
    celular: "(88) 96666-5555",
    fixo: "(88) 3677-6789",
  },

  // Crato
  {
    cidade: "Crato",
    estado: "Ceará",
    agenciaHR: "Crato RH",
    site: "https://www.cratorh.com.br/",
    email: "contato@cratorh.com.br",
    endereco: "Rua 7 de Setembro, 500. Centro.",
    celular: "(88) 99988-5555",
    fixo: "(88) 3521-2345",
  },
  {
    cidade: "Crato",
    estado: "Ceará",
    agenciaHR: "Talent Crato",
    site: "https://www.talentcrato.com.br/",
    email: "info@talentcrato.com.br",
    endereco: "Av. D. Pedro II, 300. Centro.",
    celular: "(88) 98877-4444",
    fixo: "(88) 3521-3456",
  },
  {
    cidade: "Crato",
    estado: "Ceará",
    agenciaHR: "Gente & Gestão Crato",
    site: "https://www.genteegestaocrato.com.br/",
    email: "contato@genteegestaocrato.com.br",
    endereco: "Rua da Paz, 400. Centro.",
    celular: "(88) 97777-5555",
    fixo: "(88) 3521-4567",
  },
  {
    cidade: "Crato",
    estado: "Ceará",
    agenciaHR: "Humanus Crato",
    site: "https://www.humanuscrato.com.br/",
    email: "contato@humanuscrato.com.br",
    endereco: "Av. das Palmeiras, 200. Centro.",
    celular: "(88) 95555-6666",
    fixo: "(88) 3521-5678",
  },
  {
    cidade: "Crato",
    estado: "Ceará",
    agenciaHR: "RH Crato",
    site: "https://www.rhcrato.com.br/",
    email: "contato@rhcrato.com.br",
    endereco: "Rua José de Alencar, 300. Centro.",
    celular: "(88) 96666-7777",
    fixo: "(88) 3521-6789",
  },

  // Maracanaú
  {
    cidade: "Maracanaú",
    estado: "Ceará",
    agenciaHR: "Maracanaú RH",
    site: "https://www.maracanaurh.com.br/",
    email: "contato@maracanaurh.com.br",
    endereco: "Av. Prefeito José Rodrigues, 400. Centro.",
    celular: "(85) 99988-6666",
    fixo: "(85) 3299-5544",
  },
  {
    cidade: "Maracanaú",
    estado: "Ceará",
    agenciaHR: "Talent Maracanaú",
    site: "https://www.talentmaracanau.com.br/",
    email: "info@talentmaracanau.com.br",
    endereco: "Rua do Comércio, 300. Centro.",
    celular: "(85) 98877-5555",
    fixo: "(85) 3299-6677",
  },
  {
    cidade: "Maracanaú",
    estado: "Ceará",
    agenciaHR: "Gente & Gestão Maracanaú",
    site: "https://www.genteegestaomaracanaú.com.br/",
    email: "contato@genteegestaomaracanaú.com.br",
    endereco: "Av. Subtenente José, 200. Centro.",
    celular: "(85) 97777-4444",
    fixo: "(85) 3299-7788",
  },
  {
    cidade: "Maracanaú",
    estado: "Ceará",
    agenciaHR: "Humanus Maracanaú",
    site: "https://www.humanusmaracanaú.com.br/",
    email: "contato@humanusmaracanaú.com.br",
    endereco: "Rua Pedro Jorge, 500. Centro.",
    celular: "(85) 95555-3333",
    fixo: "(85) 3299-8899",
  },
  {
    cidade: "Maracanaú",
    estado: "Ceará",
    agenciaHR: "RH Maracanaú",
    site: "https://www.rhmaracanaú.com.br/",
    email: "contato@rhmaracanaú.com.br",
    endereco: "Rua Paulo Afonso, 600. Centro.",
    celular: "(85) 96666-2222",
    fixo: "(85) 3299-9000",
  },

  // Caucaia
  {
    cidade: "Caucaia",
    estado: "Ceará",
    agenciaHR: "Caucaia RH",
    site: "https://www.caucaiarh.com.br/",
    email: "contato@caucaiarh.com.br",
    endereco: "Rua Carlos Jereissati, 700. Centro.",
    celular: "(85) 99988-4444",
    fixo: "(85) 3327-5566",
  },
  {
    cidade: "Caucaia",
    estado: "Ceará",
    agenciaHR: "Talent Caucaia",
    site: "https://www.talentcaucaia.com.br/",
    email: "info@talentcaucaia.com.br",
    endereco: "Av. São Francisco, 500. Centro.",
    celular: "(85) 98877-6666",
    fixo: "(85) 3327-6677",
  },
  {
    cidade: "Caucaia",
    estado: "Ceará",
    agenciaHR: "Gente & Gestão Caucaia",
    site: "https://www.genteegestaocaucaia.com.br/",
    email: "contato@genteegestaocaucaia.com.br",
    endereco: "Rua Manuel Cândido, 300. Centro.",
    celular: "(85) 97777-5555",
    fixo: "(85) 3327-7788",
  },
  {
    cidade: "Caucaia",
    estado: "Ceará",
    agenciaHR: "Humanus Caucaia",
    site: "https://www.humanuscaucaia.com.br/",
    email: "contato@humanuscaucaia.com.br",
    endereco: "Av. Brasil, 600. Centro.",
    celular: "(85) 95555-4444",
    fixo: "(85) 3327-8899",
  },
  {
    cidade: "Caucaia",
    estado: "Ceará",
    agenciaHR: "RH Caucaia",
    site: "https://www.rhcaucaia.com.br/",
    email: "contato@rhcaucaia.com.br",
    endereco: "Rua José Alves, 200. Centro.",
    celular: "(85) 96666-3333",
    fixo: "(85) 3327-9000",
  },

  // Iguatu
  {
    cidade: "Iguatu",
    estado: "Ceará",
    agenciaHR: "Iguatu RH",
    site: "https://www.iguaturh.com.br/",
    email: "contato@iguaturh.com.br",
    endereco: "Rua dos Trabalhadores, 600. Centro.",
    celular: "(88) 99988-3333",
    fixo: "(88) 3571-2345",
  },
  {
    cidade: "Iguatu",
    estado: "Ceará",
    agenciaHR: "Talent Iguatu",
    site: "https://www.talentiguatu.com.br/",
    email: "info@talentiguatu.com.br",
    endereco: "Av. Deputado Luís Eduardo, 700. Centro.",
    celular: "(88) 98877-4444",
    fixo: "(88) 3571-3456",
  },
  {
    cidade: "Iguatu",
    estado: "Ceará",
    agenciaHR: "Gente & Gestão Iguatu",
    site: "https://www.genteegestaiguatu.com.br/",
    email: "contato@genteegestaiguatu.com.br",
    endereco: "Rua dos Comerciários, 500. Centro.",
    celular: "(88) 97777-5555",
    fixo: "(88) 3571-4567",
  },
  {
    cidade: "Iguatu",
    estado: "Ceará",
    agenciaHR: "Humanus Iguatu",
    site: "https://www.humanusiguatu.com.br/",
    email: "contato@humanusiguatu.com.br",
    endereco: "Av. Francisco Macedo, 300. Centro.",
    celular: "(88) 95555-6666",
    fixo: "(88) 3571-5678",
  },
  {
    cidade: "Iguatu",
    estado: "Ceará",
    agenciaHR: "RH Iguatu",
    site: "https://www.rhiguatu.com.br/",
    email: "contato@rhiguatu.com.br",
    endereco: "Rua Coronel Macedo, 400. Centro.",
    celular: "(88) 96666-7777",
    fixo: "(88) 3571-6789",
  },
  // Espírito Santo
  // --------------------------------------------------------------
  // Vitória
  {
    cidade: "Vitória",
    estado: "Espírito Santo",
    agenciaHR: "VitaRH",
    site: "https://www.vitarh.com.br/",
    email: "contato@vitarh.com.br",
    endereco: "Av. Paulista, 200. Centro.",
    celular: "(27) 99999-1111",
    fixo: "(27) 3229-3344",
  },
  {
    cidade: "Vitória",
    estado: "Espírito Santo",
    agenciaHR: "RH Vitória",
    site: "https://www.rh-vitoria.com.br/",
    email: "info@rh-vitoria.com.br",
    endereco: "Rua Floriano Peixoto, 400. Centro.",
    celular: "(27) 98888-2222",
    fixo: "(27) 3229-5566",
  },
  {
    cidade: "Vitória",
    estado: "Espírito Santo",
    agenciaHR: "Gente e Gestão Vitória",
    site: "https://www.genteegestao-vitoria.com.br/",
    email: "contato@genteegestao-vitoria.com.br",
    endereco: "Av. Governador Lindemberg, 700. Centro.",
    celular: "(27) 97777-3333",
    fixo: "(27) 3229-7788",
  },
  {
    cidade: "Vitória",
    estado: "Espírito Santo",
    agenciaHR: "Talent Vitória",
    site: "https://www.talent-vitoria.com.br/",
    email: "contato@talent-vitoria.com.br",
    endereco: "Rua da Assembleia, 500. Centro.",
    celular: "(27) 96666-4444",
    fixo: "(27) 3229-8899",
  },
  {
    cidade: "Vitória",
    estado: "Espírito Santo",
    agenciaHR: "RH Solutions Vitória",
    site: "https://www.rhsolutions-vitoria.com.br/",
    email: "contato@rhsolutions-vitoria.com.br",
    endereco: "Av. Rio Branco, 800. Centro.",
    celular: "(27) 95555-5555",
    fixo: "(27) 3229-9900",
  },

  // Vila Velha
  {
    cidade: "Vila Velha",
    estado: "Espírito Santo",
    agenciaHR: "Vila RH",
    site: "https://www.vilarh.com.br/",
    email: "contato@vilarh.com.br",
    endereco: "Av. Carlos Lindenberg, 900. Centro.",
    celular: "(27) 99999-2222",
    fixo: "(27) 3337-4455",
  },
  {
    cidade: "Vila Velha",
    estado: "Espírito Santo",
    agenciaHR: "HR Vila Velha",
    site: "https://www.hr-vilavelha.com.br/",
    email: "info@hr-vilavelha.com.br",
    endereco: "Rua Desembargador Santos Neves, 600. Centro.",
    celular: "(27) 98888-3333",
    fixo: "(27) 3337-5566",
  },
  {
    cidade: "Vila Velha",
    estado: "Espírito Santo",
    agenciaHR: "Gente e Gestão Vila Velha",
    site: "https://www.genteegestao-vilavelha.com.br/",
    email: "contato@genteegestao-vilavelha.com.br",
    endereco: "Rua Praia da Costa, 500. Centro.",
    celular: "(27) 97777-4444",
    fixo: "(27) 3337-6677",
  },
  {
    cidade: "Vila Velha",
    estado: "Espírito Santo",
    agenciaHR: "Talent Vila Velha",
    site: "https://www.talent-vilavelha.com.br/",
    email: "contato@talent-vilavelha.com.br",
    endereco: "Av. Champagnat, 800. Centro.",
    celular: "(27) 96666-5555",
    fixo: "(27) 3337-7788",
  },
  {
    cidade: "Vila Velha",
    estado: "Espírito Santo",
    agenciaHR: "RH Solutions Vila Velha",
    site: "https://www.rhsolutions-vilavelha.com.br/",
    email: "contato@rhsolutions-vilavelha.com.br",
    endereco: "Rua da Glória, 300. Centro.",
    celular: "(27) 95555-6666",
    fixo: "(27) 3337-8899",
  },

  // Serra
  {
    cidade: "Serra",
    estado: "Espírito Santo",
    agenciaHR: "Serra RH",
    site: "https://www.serrarh.com.br/",
    email: "contato@serrarh.com.br",
    endereco: "Av. Talma Rodrigues, 500. Centro.",
    celular: "(27) 99999-3333",
    fixo: "(27) 3348-5566",
  },
  {
    cidade: "Serra",
    estado: "Espírito Santo",
    agenciaHR: "HR Serra",
    site: "https://www.hr-serra.com.br/",
    email: "info@hr-serra.com.br",
    endereco: "Rua dos Trabalhadores, 600. Centro.",
    celular: "(27) 98888-4444",
    fixo: "(27) 3348-6677",
  },
  {
    cidade: "Serra",
    estado: "Espírito Santo",
    agenciaHR: "Gente & Gestão Serra",
    site: "https://www.genteegestao-serra.com.br/",
    email: "contato@genteegestao-serra.com.br",
    endereco: "Av. Central, 700. Centro.",
    celular: "(27) 97777-5555",
    fixo: "(27) 3348-7788",
  },
  {
    cidade: "Serra",
    estado: "Espírito Santo",
    agenciaHR: "Talent Serra",
    site: "https://www.talent-serra.com.br/",
    email: "contato@talent-serra.com.br",
    endereco: "Rua de Jardim, 800. Centro.",
    celular: "(27) 96666-6666",
    fixo: "(27) 3348-8899",
  },
  {
    cidade: "Serra",
    estado: "Espírito Santo",
    agenciaHR: "RH Solutions Serra",
    site: "https://www.rhsolutions-serra.com.br/",
    email: "contato@rhsolutions-serra.com.br",
    endereco: "Rua da Praia, 900. Centro.",
    celular: "(27) 95555-7777",
    fixo: "(27) 3348-9900",
  },

  // Cachoeiro de Itapemirim
  {
    cidade: "Cachoeiro de Itapemirim",
    estado: "Espírito Santo",
    agenciaHR: "Cachoeiro RH",
    site: "https://www.cachoeirorh.com.br/",
    email: "contato@cachoeirorh.com.br",
    endereco: "Av. Beira Rio, 1000. Centro.",
    celular: "(28) 99999-4444",
    fixo: "(28) 3522-5678",
  },
  {
    cidade: "Cachoeiro de Itapemirim",
    estado: "Espírito Santo",
    agenciaHR: "HR Cachoeiro",
    site: "https://www.hr-cachoeiro.com.br/",
    email: "info@hr-cachoeiro.com.br",
    endereco: "Rua Afonso Pena, 600. Centro.",
    celular: "(28) 98888-5555",
    fixo: "(28) 3522-6789",
  },
  {
    cidade: "Cachoeiro de Itapemirim",
    estado: "Espírito Santo",
    agenciaHR: "Gente & Gestão Cachoeiro",
    site: "https://www.genteegestao-cachoeiro.com.br/",
    email: "contato@genteegestao-cachoeiro.com.br",
    endereco: "Av. Santo Antônio, 700. Centro.",
    celular: "(28) 97777-6666",
    fixo: "(28) 3522-7890",
  },
  {
    cidade: "Cachoeiro de Itapemirim",
    estado: "Espírito Santo",
    agenciaHR: "Talent Cachoeiro",
    site: "https://www.talent-cachoeiro.com.br/",
    email: "contato@talent-cachoeiro.com.br",
    endereco: "Rua das Flores, 800. Centro.",
    celular: "(28) 96666-7777",
    fixo: "(28) 3522-8901",
  },
  // --------------------------------------------------------------
  // --------------------------------------------------------------
  // --------------------------------------------------------------
  // --------------------------------------------------------------
  // --------------------------------------------------------------
  // --------------------------------------------------------------


  // *** Campinas / São Paulo
  {
    cidade: "Campinas",
    estado: "São Paulo",
    agenciaHR: "RH Brasil",
    site: "http://rhbrasil.com.br/",
    email: "contato@rhbrasil.com.br",
    endereco: "Av. Barão de Itapura, 1000. Guanabara.",
    celular: "(19) 99123-4455",
    fixo: "(19) 3232-1122",
  },
  {
    cidade: "Campinas",
    estado: "São Paulo",
    agenciaHR: "Workcell RH",
    site: "http://workcell.com.br/",
    email: "faleconosco@workcell.com.br",
    endereco: "Rua Conceição, 450. Centro.",
    celular: "(19) 99877-5544",
    fixo: "(19) 3303-5544",
  },
  {
    cidade: "Campinas",
    estado: "São Paulo",
    agenciaHR: "Grupo Selpe",
    site: "http://gruposelpe.com.br/",
    email: "contato@gruposelpe.com.br",
    endereco: "Av. Anchieta, 800. Centro.",
    celular: "(19) 99555-2233",
    fixo: "(19) 3304-9988",
  },
  {
    cidade: "Campinas",
    estado: "São Paulo",
    agenciaHR: "Randstad",
    site: "http://randstad.com.br/",
    email: "atendimento@randstad.com.br",
    endereco: "Rua José Paulino, 1200. Centro.",
    celular: "(19) 99212-6655",
    fixo: "(19) 3234-7788",
  },
  {
    cidade: "Campinas",
    estado: "São Paulo",
    agenciaHR: "Luandre RH",
    site: "http://luandre.com.br/",
    email: "falecom@luandre.com.br",
    endereco: "Av. Júlio de Mesquita, 300. Cambuí.",
    celular: "(19) 99334-5566",
    fixo: "(19) 3344-1133",
  },
  {
    cidade: "Campinas",
    estado: "São Paulo",
    agenciaHR: "Global Empregos",
    site: "http://globalempregos.com.br/",
    email: "contato@globalempregos.com.br",
    endereco: "Rua Dr. Quirino, 1500. Centro.",
    celular: "(19) 99444-6677",
    fixo: "(19) 3233-1199",
  },
  {
    cidade: "Campinas",
    estado: "São Paulo",
    agenciaHR: "Adecco Brasil",
    site: "http://adecco.com.br/",
    email: "info@adecco.com.br",
    endereco: "Av. Francisco Glicério, 1750. Centro.",
    celular: "(19) 99666-7788",
    fixo: "(19) 3221-1122",
  },
  {
    cidade: "Campinas",
    estado: "São Paulo",
    agenciaHR: "Gi Group",
    site: "http://gigroup.com.br/",
    email: "atendimento@gigroup.com.br",
    endereco: "Rua General Osório, 1800. Centro.",
    celular: "(19) 99555-9988",
    fixo: "(19) 3302-6677",
  },
  {
    cidade: "Campinas",
    estado: "São Paulo",
    agenciaHR: "Manpower",
    site: "http://manpower.com.br/",
    email: "contato@manpower.com.br",
    endereco: "Rua Barão de Jaguara, 1456. Centro.",
    celular: "(19) 99444-4455",
    fixo: "(19) 3231-4455",
  },
  {
    cidade: "Campinas",
    estado: "São Paulo",
    agenciaHR: "Grupo Seres",
    site: "http://gruposeres.com.br/",
    email: "info@gruposeres.com.br",
    endereco: "Av. Orosimbo Maia, 800. Cambuí.",
    celular: "(19) 99321-1234",
    fixo: "(19) 3244-7788",
  },
  {
    cidade: "Campinas",
    estado: "São Paulo",
    agenciaHR: "Consultoria Soluções",
    site: "http://consultoriasolucoes.com.br/",
    email: "contato@consultoriasolucoes.com.br",
    endereco: "Rua Dona Libânia, 910. Centro.",
    celular: "(19) 99567-8899",
    fixo: "(19) 3303-5566",
  },
  {
    cidade: "Campinas",
    estado: "São Paulo",
    agenciaHR: "Kelly Services",
    site: "http://kellyservices.com.br/",
    email: "faleconosco@kellyservices.com.br",
    endereco: "Rua Ferreira Penteado, 1245. Cambuí.",
    celular: "(19) 99223-3344",
    fixo: "(19) 3211-6677",
  },
  {
    cidade: "Campinas",
    estado: "São Paulo",
    agenciaHR: "Talento RH",
    site: "http://talentorh.com.br/",
    email: "info@talentorh.com.br",
    endereco: "Rua Emílio Ribas, 900. Centro.",
    celular: "(19) 99322-5566",
    fixo: "(19) 3223-1133",
  },
  {
    cidade: "Campinas",
    estado: "São Paulo",
    agenciaHR: "Assertiva RH",
    site: "http://assertivarh.com.br/",
    email: "contato@assertivarh.com.br",
    endereco: "Rua Coronel Quirino, 567. Cambuí.",
    celular: "(19) 99112-3344",
    fixo: "(19) 3304-9988",
  },
  {
    cidade: "Campinas",
    estado: "São Paulo",
    agenciaHR: "JobLine",
    site: "http://jobline.com.br/",
    email: "contato@jobline.com.br",
    endereco: "Av. Andrade Neves, 700. Vila Itapura.",
    celular: "(19) 99534-2233",
    fixo: "(19) 3234-1133",
  },
  {
    cidade: "Campinas",
    estado: "São Paulo",
    agenciaHR: "Meta RH",
    site: "http://metarh.com.br/",
    email: "faleconosco@metarh.com.br",
    endereco: "Rua Antonio Cesarino, 980. Centro.",
    celular: "(19) 99221-2234",
    fixo: "(19) 3302-3344",
  },
  {
    cidade: "Campinas",
    estado: "São Paulo",
    agenciaHR: "Maxim RH",
    site: "http://maximrh.com.br/",
    email: "atendimento@maximrh.com.br",
    endereco: "Rua Abolição, 1290. Guanabara.",
    celular: "(19) 99345-6677",
    fixo: "(19) 3223-5566",
  },
  {
    cidade: "Campinas",
    estado: "São Paulo",
    agenciaHR: "Impact RH",
    site: "http://impactrh.com.br/",
    email: "info@impactrh.com.br",
    endereco: "Av. Brasil, 1450. Jardim Chapadão.",
    celular: "(19) 99432-1133",
    fixo: "(19) 3344-7788",
  },
  {
    cidade: "Campinas",
    estado: "São Paulo",
    agenciaHR: "Up RH",
    site: "http://uprh.com.br/",
    email: "contato@uprh.com.br",
    endereco: "Rua Luzitana, 1250. Botafogo.",
    celular: "(19) 99666-3344",
    fixo: "(19) 3232-4455",
  },
  {
    cidade: "Campinas",
    estado: "São Paulo",
    agenciaHR: "Confidencial RH",
    site: "http://confidencialrh.com.br/",
    email: "contato@confidencialrh.com.br",
    endereco: "Av. Júlio Prestes, 345. Bonfim.",
    celular: "(19) 99112-7788",
    fixo: "(19) 3304-5566",
  },
  {
    cidade: "Campinas",
    estado: "São Paulo",
    agenciaHR: "Conquista RH",
    site: "http://conquistarh.com.br/",
    email: "faleconosco@conquistarh.com.br",
    endereco: "Rua José de Alencar, 600. Cambuí.",
    celular: "(19) 99212-8899",
    fixo: "(19) 3231-3344",
  },
  {
    cidade: "Campinas",
    estado: "São Paulo",
    agenciaHR: "Eldorado Recursos Humanos",
    site: "http://eldoradorh.com.br/",
    email: "contato@eldoradorh.com.br",
    endereco: "Rua Conceição, 233. Centro.",
    celular: "(19) 99888-1111",
    fixo: "(19) 3234-4455",
  },
  {
    cidade: "Campinas",
    estado: "São Paulo",
    agenciaHR: "Expert Consultoria",
    site: "https://www.expertrh.com.br/",
    email: "atendimento@expertrh.com.br",
    endereco: "Av. Orosimbo Maia, 180. Cambuí.",
    celular: "(19) 99344-1122",
    fixo: "(19) 3302-4455",
  },
  {
    cidade: "Campinas",
    estado: "São Paulo",
    agenciaHR: "Captativa RH",
    site: "http://www.captativa.com.br/",
    email: "faleconosco@captativa.com.br",
    endereco: "Rua José de Alencar, 450. Cambuí.",
    celular: "(19) 99344-1122",
    fixo: "(19) 3302-9988",
  },
  // *** São Paulo / São Paulo
  {
    cidade: "São Paulo",
    estado: "São Paulo",
    agenciaHR: "Page Personnel",
    site: "https://www.pagepersonnel.com.br/",
    email: "contato@pagepersonnel.com.br",
    endereco: "Av. Brigadeiro Faria Lima, 3144. Itaim Bibi.",
    celular: "(11) 99999-0000",
    fixo: "(11) 3003-5200",
  },
  {
    cidade: "São Paulo",
    estado: "São Paulo",
    agenciaHR: "Robert Half",
    site: "https://www.roberthalf.com.br/",
    email: "info@roberthalf.com.br",
    endereco: "Av. Paulista, 1079. Bela Vista.",
    celular: "(11) 98888-1111",
    fixo: "(11) 3388-0000",
  },
  {
    cidade: "São Paulo",
    estado: "São Paulo",
    agenciaHR: "Michael Page",
    site: "https://www.michaelpage.com.br/",
    email: "contato@michaelpage.com.br",
    endereco: "Rua Funchal, 418. Vila Olímpia.",
    celular: "(11) 97777-2222",
    fixo: "(11) 3046-7575",
  },
  {
    cidade: "São Paulo",
    estado: "São Paulo",
    agenciaHR: "ManpowerGroup",
    site: "https://www.manpowergroup.com.br/",
    email: "atendimento@manpowergroup.com.br",
    endereco: "Av. Paulista, 2300. Bela Vista.",
    celular: "(11) 97777-3333",
    fixo: "(11) 3285-8000",
  },
  {
    cidade: "São Paulo",
    estado: "São Paulo",
    agenciaHR: "Gi Group Brasil",
    site: "https://br.gigroup.com/",
    email: "info@gigroup.com.br",
    endereco: "Av. São João, 240. República.",
    celular: "(11) 98888-4444",
    fixo: "(11) 3046-9500",
  },
  {
    cidade: "São Paulo",
    estado: "São Paulo",
    agenciaHR: "Randstad Brasil",
    site: "https://www.randstad.com.br/",
    email: "contato@randstad.com.br",
    endereco: "Rua Funchal, 538. Vila Olímpia.",
    celular: "(11) 95555-5566",
    fixo: "(11) 3095-7575",
  },
  {
    cidade: "São Paulo",
    estado: "São Paulo",
    agenciaHR: "Adecco Brasil",
    site: "https://www.adecco.com.br/",
    email: "info@adecco.com.br",
    endereco: "Rua Verbo Divino, 2001. Chácara Santo Antônio.",
    celular: "(11) 97777-6677",
    fixo: "(11) 5508-8800",
  },
  {
    cidade: "São Paulo",
    estado: "São Paulo",
    agenciaHR: "Luandre",
    site: "https://www.luandre.com.br/",
    email: "contato@luandre.com.br",
    endereco: "Rua Sete de Abril, 230. República.",
    celular: "(11) 99988-1234",
    fixo: "(11) 3297-8000",
  },
  {
    cidade: "São Paulo",
    estado: "São Paulo",
    agenciaHR: "Kenoby",
    site: "https://www.kenoby.com/",
    email: "contato@kenoby.com.br",
    endereco: "Av. Engenheiro Luís Carlos Berrini, 550. Brooklin.",
    celular: "(11) 99977-3344",
    fixo: "(11) 3405-2200",
  },
  {
    cidade: "São Paulo",
    estado: "São Paulo",
    agenciaHR: "Meta RH",
    site: "http://metarh.com.br/",
    email: "atendimento@metarh.com.br",
    endereco: "Rua Dr. Renato Paes de Barros, 719. Itaim Bibi.",
    celular: "(11) 97777-2233",
    fixo: "(11) 3078-7575",
  },
  // *** Sorocaba / São Paulo
  {
    cidade: "Sorocaba",
    estado: "São Paulo",
    agenciaHR: "Auxilia RH",
    site: "http://auxiliarh.com.br/",
    email: "contato@auxiliarh.com.br",
    endereco: "Rua Antônio Carlos Comitre, 270. Campolim.",
    celular: "(15) 99666-3333",
    fixo: "(15) 3322-4455",
  },
  // *** São José dos Campos / São Paulo
  {
    cidade: "São José dos Campos",
    estado: "São Paulo",
    agenciaHR: "Gelre RH",
    site: "https://www.gelre.com.br/",
    email: "contato@gelre.com.br",
    endereco: "Av. Dr. João Batista Soares de Queiroz Júnior, 305. Jardim Satélite.",
    celular: "(12) 99665-5544",
    fixo: "(12) 3933-5566",
  },
  // *** São Bernardo do Campo / São Paulo
  {
    cidade: "São Bernardo do Campo",
    estado: "São Paulo",
    agenciaHR: "Atento",
    site: "https://www.atento.com/",
    email: "falecom@atento.com.br",
    endereco: "Rua João Firmino, 258. Centro.",
    celular: "(11) 96677-4455",
    fixo: "(11) 2107-1234",
  },
  // *** Barueri / São Paulo
  {
    cidade: "Barueri",
    estado: "São Paulo",
    agenciaHR: "Sodexo Benefícios",
    site: "https://www.sodexobeneficios.com.br/",
    email: "atendimento@sodexo.com.br",
    endereco: "Av. Tamboré, 267. Alphaville.",
    celular: "(11) 95555-6677",
    fixo: "(11) 5509-1234",
  },
  // *** Ribeirão Preto / São Paulo
  {
    cidade: "Ribeirão Preto",
    estado: "São Paulo",
    agenciaHR: "Trilha Empregos",
    site: "https://www.trilhaempregos.com.br/",
    email: "info@trilhaempregos.com.br",
    endereco: "Rua Bernardino de Campos, 150. Centro.",
    celular: "(16) 99888-1122",
    fixo: "(16) 3232-3344",
  },
  // *** Piracicaba / São Paulo
  {
    cidade: "Piracicaba",
    estado: "São Paulo",
    agenciaHR: "Maxim RH",
    site: "http://maximrh.com.br/",
    email: "info@maximrh.com.br",
    endereco: "Rua Benjamin Constant, 1944. Centro.",
    celular: "(19) 99877-4455",
    fixo: "(19) 3304-6677",
  },
  // *** Jundiaí / São Paulo
  {
    cidade: "Jundiaí",
    estado: "São Paulo",
    agenciaHR: "Solucionar RH",
    site: "http://solucionarrh.com.br/",
    email: "faleconosco@solucionarrh.com.br",
    endereco: "Rua do Retiro, 500. Vila Virginia.",
    celular: "(11) 96677-2233",
    fixo: "(11) 4521-3344",
  },
  // *** Rio de Janeiro / Rio de Janeiro
  {
    cidade: "Rio de Janeiro",
    estado: "Rio de Janeiro",
    agenciaHR: "Michael Page",
    site: "https://www.michaelpage.com.br/",
    email: "contato@michaelpage.com.br",
    endereco: "Av. Almirante Barroso, 81. Centro.",
    celular: "(21) 98888-1111",
    fixo: "(21) 3046-7575",
  },
  {
    cidade: "Rio de Janeiro",
    estado: "Rio de Janeiro",
    agenciaHR: "Robert Half",
    site: "https://www.roberthalf.com.br/",
    email: "info@roberthalf.com.br",
    endereco: "Av. Rio Branco, 125. Centro.",
    celular: "(21) 99777-2222",
    fixo: "(21) 3388-0000",
  },
  {
    cidade: "Rio de Janeiro",
    estado: "Rio de Janeiro",
    agenciaHR: "Page Personnel",
    site: "https://www.pagepersonnel.com.br/",
    email: "contato@pagepersonnel.com.br",
    endereco: "Rua Sete de Setembro, 111. Centro.",
    celular: "(21) 96666-3333",
    fixo: "(21) 3003-5200",
  },
  {
    cidade: "Rio de Janeiro",
    estado: "Rio de Janeiro",
    agenciaHR: "ManpowerGroup",
    site: "https://www.manpowergroup.com.br/",
    email: "atendimento@manpowergroup.com.br",
    endereco: "Rua Primeiro de Março, 23. Centro.",
    celular: "(21) 97777-4444",
    fixo: "(21) 3285-8000",
  },
  {
    cidade: "Rio de Janeiro",
    estado: "Rio de Janeiro",
    agenciaHR: "Gi Group Brasil",
    site: "https://br.gigroup.com/",
    email: "info@gigroup.com.br",
    endereco: "Av. Presidente Vargas, 1001. Centro.",
    celular: "(21) 98888-5555",
    fixo: "(21) 3046-9500",
  },
  {
    cidade: "Rio de Janeiro",
    estado: "Rio de Janeiro",
    agenciaHR: "Randstad Brasil",
    site: "https://www.randstad.com.br/",
    email: "contato@randstad.com.br",
    endereco: "Rua da Assembleia, 10. Centro.",
    celular: "(21) 95555-6666",
    fixo: "(21) 3095-7575",
  },
  {
    cidade: "Rio de Janeiro",
    estado: "Rio de Janeiro",
    agenciaHR: "Adecco Brasil",
    site: "https://www.adecco.com.br/",
    email: "info@adecco.com.br",
    endereco: "Av. Rio Branco, 133. Centro.",
    celular: "(21) 97777-7777",
    fixo: "(21) 5508-8800",
  },
  {
    cidade: "Rio de Janeiro",
    estado: "Rio de Janeiro",
    agenciaHR: "Luandre",
    site: "https://www.luandre.com.br/",
    email: "contato@luandre.com.br",
    endereco: "Rua México, 45. Centro.",
    celular: "(21) 99988-8888",
    fixo: "(21) 3297-8000",
  },
  {
    cidade: "Rio de Janeiro",
    estado: "Rio de Janeiro",
    agenciaHR: "Grupo Selpe",
    site: "https://gruposelpe.com.br/",
    email: "contato@gruposelpe.com.br",
    endereco: "Av. das Américas, 5000. Barra da Tijuca.",
    celular: "(21) 98888-9999",
    fixo: "(21) 3433-0000",
  },
  {
    cidade: "Rio de Janeiro",
    estado: "Rio de Janeiro",
    agenciaHR: "Grupo Soulan",
    site: "https://www.soulan.com.br/",
    email: "contato@soulan.com.br",
    endereco: "Av. das Américas, 3500. Barra da Tijuca.",
    celular: "(21) 96677-1122",
    fixo: "(21) 3033-4455",
  },
  {
    cidade: "Rio de Janeiro",
    estado: "Rio de Janeiro",
    agenciaHR: "Fator RH",
    site: "https://www.fatorrh.com.br/",
    email: "contato@fatorrh.com.br",
    endereco: "Rua Senador Dantas, 74. Centro.",
    celular: "(21) 99777-3344",
    fixo: "(21) 2233-7788",
  },
  {
    cidade: "Rio de Janeiro",
    estado: "Rio de Janeiro",
    agenciaHR: "Top Quality RH",
    site: "http://www.topqualityrh.com.br/",
    email: "contato@topqualityrh.com.br",
    endereco: "Rua Visconde de Inhaúma, 134. Centro.",
    celular: "(21) 98888-2233",
    fixo: "(21) 2508-8800",
  },
  {
    cidade: "Rio de Janeiro",
    estado: "Rio de Janeiro",
    agenciaHR: "Parceria Consultoria",
    site: "https://www.parceriaconsult.com.br/",
    email: "contato@parceriaconsult.com.br",
    endereco: "Rua Teófilo Otoni, 31. Centro.",
    celular: "(21) 95555-6677",
    fixo: "(21) 2507-9988",
  },
  {
    cidade: "Rio de Janeiro",
    estado: "Rio de Janeiro",
    agenciaHR: "Cia de Talentos",
    site: "https://www.ciadetalentos.com.br/",
    email: "contato@ciadetalentos.com.br",
    endereco: "Rua da Quitanda, 50. Centro.",
    celular: "(21) 98877-1122",
    fixo: "(21) 3233-4455",
  },
  {
    cidade: "Rio de Janeiro",
    estado: "Rio de Janeiro",
    agenciaHR: "Consultoria Gesta",
    site: "http://www.consultoriagesta.com.br/",
    email: "contato@consultoriagesta.com.br",
    endereco: "Rua Visconde de Pirajá, 495. Ipanema.",
    celular: "(21) 99777-4455",
    fixo: "(21) 2239-6677",
  },
  {
    cidade: "Rio de Janeiro",
    estado: "Rio de Janeiro",
    agenciaHR: "Brasil Brokers RH",
    site: "https://www.brasilbrokersrh.com.br/",
    email: "contato@brasilbrokersrh.com.br",
    endereco: "Av. Presidente Vargas, 2000. Centro.",
    celular: "(21) 96666-5566",
    fixo: "(21) 3202-1122",
  },
  {
    cidade: "Rio de Janeiro",
    estado: "Rio de Janeiro",
    agenciaHR: "TalenTI",
    site: "https://www.talenti.com.br/",
    email: "contato@talenti.com.br",
    endereco: "Rua do Ouvidor, 60. Centro.",
    celular: "(21) 95555-7788",
    fixo: "(21) 3099-3322",
  },
  {
    cidade: "Rio de Janeiro",
    estado: "Rio de Janeiro",
    agenciaHR: "Elevus",
    site: "https://www.elevus.com.br/",
    email: "contato@elevus.com.br",
    endereco: "Av. Rio Branco, 210. Centro.",
    celular: "(21) 98888-3344",
    fixo: "(21) 3094-5566",
  },
  {
    cidade: "Rio de Janeiro",
    estado: "Rio de Janeiro",
    agenciaHR: "RH Service",
    site: "https://www.rhservice.com.br/",
    email: "contato@rhservice.com.br",
    endereco: "Rua México, 180. Centro.",
    celular: "(21) 97777-5566",
    fixo: "(21) 2205-8800",
  },
  {
    cidade: "Rio de Janeiro",
    estado: "Rio de Janeiro",
    agenciaHR: "Alliance Consultoria",
    site: "https://www.allianceconsultoria.com.br/",
    email: "contato@allianceconsultoria.com.br",
    endereco: "Rua da Glória, 44. Glória.",
    celular: "(21) 96677-7788",
    fixo: "(21) 2232-4455",
  },

  // São Paulo
  {
    cidade: "São Paulo",
    estado: "São Paulo",
    agenciaHR: "Michael Page",
    site: "https://www.michaelpage.com.br/",
    email: "contato@michaelpage.com.br",
    endereco: "Av. Paulista, 1106. Bela Vista.",
    celular: "(11) 99988-2233",
    fixo: "(11) 4003-7575",
  },
  {
    cidade: "São Paulo",
    estado: "São Paulo",
    agenciaHR: "Robert Half",
    site: "https://www.roberthalf.com.br/",
    email: "info@roberthalf.com.br",
    endereco: "Av. Brigadeiro Faria Lima, 1300. Itaim Bibi.",
    celular: "(11) 95555-3344",
    fixo: "(11) 3388-0000",
  },
  {
    cidade: "São Paulo",
    estado: "São Paulo",
    agenciaHR: "Randstad Brasil",
    site: "https://www.randstad.com.br/",
    email: "contato@randstad.com.br",
    endereco: "Av. das Nações Unidas, 8501. Pinheiros.",
    celular: "(11) 96666-5566",
    fixo: "(11) 3095-7575",
  },
  {
    cidade: "São Paulo",
    estado: "São Paulo",
    agenciaHR: "Luandre",
    site: "https://www.luandre.com.br/",
    email: "contato@luandre.com.br",
    endereco: "Av. Ipiranga, 200. Centro.",
    celular: "(11) 97777-1122",
    fixo: "(11) 3297-8000",
  },
  {
    cidade: "São Paulo",
    estado: "São Paulo",
    agenciaHR: "Gi Group Brasil",
    site: "https://br.gigroup.com/",
    email: "info@gigroup.com.br",
    endereco: "Av. Paulista, 2200. Consolação.",
    celular: "(11) 98888-3344",
    fixo: "(11) 3046-9500",
  },

  // Rio de Janeiro
  {
    cidade: "Rio de Janeiro",
    estado: "Rio de Janeiro",
    agenciaHR: "Parceria Consultoria",
    site: "https://www.parceriaconsult.com.br/",
    email: "contato@parceriaconsult.com.br",
    endereco: "Rua Teófilo Otoni, 31. Centro.",
    celular: "(21) 95555-6677",
    fixo: "(21) 2507-9988",
  },
  {
    cidade: "Rio de Janeiro",
    estado: "Rio de Janeiro",
    agenciaHR: "Cia de Talentos",
    site: "https://www.ciadetalentos.com.br/",
    email: "contato@ciadetalentos.com.br",
    endereco: "Rua da Quitanda, 50. Centro.",
    celular: "(21) 98877-1122",
    fixo: "(21) 3233-4455",
  },
  {
    cidade: "Rio de Janeiro",
    estado: "Rio de Janeiro",
    agenciaHR: "Top Quality RH",
    site: "http://www.topqualityrh.com.br/",
    email: "contato@topqualityrh.com.br",
    endereco: "Rua Visconde de Inhaúma, 134. Centro.",
    celular: "(21) 98888-2233",
    fixo: "(21) 2508-8800",
  },
  {
    cidade: "Rio de Janeiro",
    estado: "Rio de Janeiro",
    agenciaHR: "ManpowerGroup Rio",
    site: "https://www.manpowergroup.com.br/",
    email: "rio@manpowergroup.com.br",
    endereco: "Av. Presidente Vargas, 1001. Centro.",
    celular: "(21) 99999-2233",
    fixo: "(21) 3285-8000",
  },
  {
    cidade: "Rio de Janeiro",
    estado: "Rio de Janeiro",
    agenciaHR: "Randstad Brasil RJ",
    site: "https://www.randstad.com.br/",
    email: "contato@randstad.com.br",
    endereco: "Rua da Assembleia, 10. Centro.",
    celular: "(21) 95555-6666",
    fixo: "(21) 3095-7575",
  },

  // Minas Gerais
  {
    cidade: "Belo Horizonte",
    estado: "Minas Gerais",
    agenciaHR: "Employer BH",
    site: "https://www.employer.com.br/",
    email: "contato@employer.com.br",
    endereco: "Av. Amazonas, 1234. Centro.",
    celular: "(31) 98888-2233",
    fixo: "(31) 3333-4444",
  },
  {
    cidade: "Belo Horizonte",
    estado: "Minas Gerais",
    agenciaHR: "Gi Group BH",
    site: "https://br.gigroup.com/",
    email: "bh@gigroup.com.br",
    endereco: "Av. do Contorno, 4567. Barro Preto.",
    celular: "(31) 95555-6677",
    fixo: "(31) 3046-9500",
  },
  {
    cidade: "Belo Horizonte",
    estado: "Minas Gerais",
    agenciaHR: "Randstad BH",
    site: "https://www.randstad.com.br/",
    email: "bh@randstad.com.br",
    endereco: "Av. Afonso Pena, 234. Centro.",
    celular: "(31) 96666-5566",
    fixo: "(31) 3333-6677",
  },
  {
    cidade: "Belo Horizonte",
    estado: "Minas Gerais",
    agenciaHR: "Grupo Selpe BH",
    site: "https://gruposelpe.com.br/",
    email: "contato@gruposelpe.com.br",
    endereco: "Rua dos Guajajaras, 1000. Lourdes.",
    celular: "(31) 97777-7788",
    fixo: "(31) 3333-7788",
  },
  {
    cidade: "Belo Horizonte",
    estado: "Minas Gerais",
    agenciaHR: "Empregar BH",
    site: "https://www.empregarbh.com.br/",
    email: "contato@empregarbh.com.br",
    endereco: "Rua Tupinambás, 200. Centro.",
    celular: "(31) 96666-8899",
    fixo: "(31) 3333-8899",
  },
  // Paraná
  {
    cidade: "Curitiba",
    estado: "Paraná",
    agenciaHR: "RH Curitiba",
    site: "https://www.rhcuritiba.com.br/",
    email: "contato@rhcuritiba.com.br",
    endereco: "Av. Marechal Floriano Peixoto, 450. Centro.",
    celular: "(41) 98888-5566",
    fixo: "(41) 3333-4455",
  },
  {
    cidade: "Curitiba",
    estado: "Paraná",
    agenciaHR: "Agnes RH",
    site: "https://agnesrh.com.br/",
    email: "contato@agnesrh.com.br",
    endereco: "Rua Conselheiro Laurindo, 800. Centro.",
    celular: "(41) 99988-6677",
    fixo: "(41) 3333-5566",
  },
  {
    cidade: "Curitiba",
    estado: "Paraná",
    agenciaHR: "FIEP RH",
    site: "https://www.fieprh.org.br/",
    email: "contato@fieprh.org.br",
    endereco: "Av. Cândido de Abreu, 200. Centro Cívico.",
    celular: "(41) 95555-7788",
    fixo: "(41) 3333-6677",
  },
  {
    cidade: "Curitiba",
    estado: "Paraná",
    agenciaHR: "Grupo Cetefe",
    site: "http://grupocetefe.com.br/",
    email: "contato@grupocetefe.com.br",
    endereco: "Rua Dr. Pedrosa, 300. Centro.",
    celular: "(41) 98888-2233",
    fixo: "(41) 3333-7788",
  },
  {
    cidade: "Curitiba",
    estado: "Paraná",
    agenciaHR: "Desidy",
    site: "https://www.desidy.com.br/",
    email: "contato@desidy.com.br",
    endereco: "Rua Comendador Araújo, 130. Centro.",
    celular: "(41) 95555-8899",
    fixo: "(41) 3333-8899",
  },
  {
    cidade: "Recife",
    estado: "Pernambuco",
    agenciaHR: "Grupo Foco",
    site: "https://www.grupofoco.com.br/",
    email: "contato@grupofoco.com.br",
    endereco: "Av. Agamenon Magalhães, 280. Graças.",
    celular: "(81) 96666-5566",
    fixo: "(81) 3333-6677",
  },
  {
    cidade: "Recife",
    estado: "Pernambuco",
    agenciaHR: "Talent RH",
    site: "https://www.talentrh.com.br/",
    email: "contato@talentrh.com.br",
    endereco: "Rua da Aurora, 150. Centro.",
    celular: "(81) 97777-8899",
    fixo: "(81) 3333-7788",
  },
  {
    cidade: "Recife",
    estado: "Pernambuco",
    agenciaHR: "Estrategia RH",
    site: "https://www.estrategiarh.com.br/",
    email: "contato@estrategiarh.com.br",
    endereco: "Av. Visconde de Suassuna, 120. Boa Vista.",
    celular: "(81) 95555-8899",
    fixo: "(81) 3333-8899",
  },
  // Ceará
  {
    cidade: "Fortaleza",
    estado: "Ceará",
    agenciaHR: "RH Fortaleza",
    site: "https://www.rhfortaleza.com.br/",
    email: "contato@rhfortaleza.com.br",
    endereco: "Av. Dom Luís, 3000. Aldeota.",
    celular: "(85) 98888-2233",
    fixo: "(85) 3333-4455",
  },
  {
    cidade: "Fortaleza",
    estado: "Ceará",
    agenciaHR: "Desenvolver RH",
    site: "https://www.desenvolver.com.br/",
    email: "contato@desenvolver.com.br",
    endereco: "Rua Monsenhor Tabosa, 100. Centro.",
    celular: "(85) 99988-6677",
    fixo: "(85) 3333-5566",
  },
  {
    cidade: "Fortaleza",
    estado: "Ceará",
    agenciaHR: "Grupo RH Ceará",
    site: "https://www.gruporhce.com.br/",
    email: "contato@gruporhce.com.br",
    endereco: "Av. Washington Soares, 800. Edson Queiroz.",
    celular: "(85) 96666-5566",
    fixo: "(85) 3333-6677",
  },
  {
    cidade: "Fortaleza",
    estado: "Ceará",
    agenciaHR: "Emprego Mais",
    site: "https://www.empregomais.com.br/",
    email: "contato@empregomais.com.br",
    endereco: "Rua José Avelino, 500. Centro.",
    celular: "(85) 97777-8899",
    fixo: "(85) 3333-7788",
  },
  {
    cidade: "Fortaleza",
    estado: "Ceará",
    agenciaHR: "Talent Search",
    site: "https://www.talentsearchce.com.br/",
    email: "contato@talentsearchce.com.br",
    endereco: "Rua Henrique Júnior, 200. Meireles.",
    celular: "(85) 95555-8899",
    fixo: "(85) 3333-8899",
  },
  // Rio Grande do Sul
  {
    cidade: "Porto Alegre",
    estado: "Rio Grande do Sul",
    agenciaHR: "RH Porto Alegre",
    site: "https://www.rhportoa.com.br/",
    email: "contato@rhportoa.com.br",
    endereco: "Av. Carlos Gomes, 1200. Bela Vista.",
    celular: "(51) 98888-2233",
    fixo: "(51) 3333-4455",
  },
  {
    cidade: "Porto Alegre",
    estado: "Rio Grande do Sul",
    agenciaHR: "Vagas RH",
    site: "https://www.vagasrh.com.br/",
    email: "contato@vagasrh.com.br",
    endereco: "Rua da República, 300. Centro.",
    celular: "(51) 99988-6677",
    fixo: "(51) 3333-5566",
  },
  {
    cidade: "Porto Alegre",
    estado: "Rio Grande do Sul",
    agenciaHR: "Talent RH",
    site: "https://www.talentrh.com.br/",
    email: "contato@talentrh.com.br",
    endereco: "Rua Fernando Machado, 500. Centro.",
    celular: "(51) 96666-5566",
    fixo: "(51) 3333-6677",
  },
  {
    cidade: "Porto Alegre",
    estado: "Rio Grande do Sul",
    agenciaHR: "Gente e Gestão",
    site: "https://www.genteegestao.com.br/",
    email: "contato@genteegestao.com.br",
    endereco: "Av. Ipiranga, 2000. Independência.",
    celular: "(51) 97777-8899",
    fixo: "(51) 3333-7788",
  },
  {
    cidade: "Porto Alegre",
    estado: "Rio Grande do Sul",
    agenciaHR: "HRSolutions",
    site: "https://www.hrsolutionsrs.com.br/",
    email: "contato@hrsolutionsrs.com.br",
    endereco: "Rua São Pedro, 150. Centro.",
    celular: "(51) 95555-8899",
    fixo: "(51) 3333-8899",
  },

  // Goiás
  {
    cidade: "Goiânia",
    estado: "Goiás",
    agenciaHR: "RH Goiânia",
    site: "https://www.rhgoiania.com.br/",
    email: "contato@rhgoiania.com.br",
    endereco: "Av. Goiás, 1000. Setor Central.",
    celular: "(62) 98888-2233",
    fixo: "(62) 3333-4455",
  },
  {
    cidade: "Goiânia",
    estado: "Goiás",
    agenciaHR: "Goiás Talent",
    site: "https://www.goias-talent.com.br/",
    email: "contato@goias-talent.com.br",
    endereco: "Rua 4, 300. Centro.",
    celular: "(62) 99988-6677",
    fixo: "(62) 3333-5566",
  },
  {
    cidade: "Goiânia",
    estado: "Goiás",
    agenciaHR: "Viva RH",
    site: "https://www.vivarh.com.br/",
    email: "contato@vivarh.com.br",
    endereco: "Av. Araguaia, 500. Setor Oeste.",
    celular: "(62) 96666-5566",
    fixo: "(62) 3333-6677",
  },
  {
    cidade: "Goiânia",
    estado: "Goiás",
    agenciaHR: "Goiás Recrutamento",
    site: "https://www.goiasrecrutamento.com.br/",
    email: "contato@goiasrecrutamento.com.br",
    endereco: "Rua 5, 600. Jardim Goiás.",
    celular: "(62) 97777-8899",
    fixo: "(62) 3333-7788",
  },
  {
    cidade: "Goiânia",
    estado: "Goiás",
    agenciaHR: "Empregos Goiás",
    site: "https://www.empregosgoias.com.br/",
    email: "contato@empregosgoias.com.br",
    endereco: "Av. 85, 1000. Setor Marista.",
    celular: "(62) 95555-8899",
    fixo: "(62) 3333-8899",
  },
  // Distrito Federal
  {
    cidade: "Brasília",
    estado: "Distrito Federal",
    agenciaHR: "RH Brasília",
    site: "https://www.rhbrasilia.com.br/",
    email: "contato@rhbrasilia.com.br",
    endereco: "SBS Quadra 2, Bloco H. Asa Sul.",
    celular: "(61) 98888-2233",
    fixo: "(61) 3333-4455",
  },
  {
    cidade: "Brasília",
    estado: "Distrito Federal",
    agenciaHR: "Talent DF",
    site: "https://www.talentdf.com.br/",
    email: "contato@talentdf.com.br",
    endereco: "SCLN 115, Bloco C. Asa Norte.",
    celular: "(61) 99988-6677",
    fixo: "(61) 3333-5566",
  },
  {
    cidade: "Brasília",
    estado: "Distrito Federal",
    agenciaHR: "Gente e Gestão Brasília",
    site: "https://www.genteegestaodf.com.br/",
    email: "contato@genteegestaodf.com.br",
    endereco: "QMS 104, Bloco D. Guará.",
    celular: "(61) 96666-5566",
    fixo: "(61) 3333-6677",
  },
  {
    cidade: "Brasília",
    estado: "Distrito Federal",
    agenciaHR: "Grupo HRS",
    site: "https://www.grupohrs.com.br/",
    email: "contato@grupohrs.com.br",
    endereco: "QSB 105, Bloco A. Santa Maria.",
    celular: "(61) 97777-8899",
    fixo: "(61) 3333-7788",
  },
  {
    cidade: "Brasília",
    estado: "Distrito Federal",
    agenciaHR: "BR RH",
    site: "https://www.br-rh.com.br/",
    email: "contato@br-rh.com.br",
    endereco: "SBS Quadra 3, Bloco B. Asa Sul.",
    celular: "(61) 95555-8899",
    fixo: "(61) 3333-8899",
  },
  // *** Manaus / Amazonas
];

